# Generated by Django 6.0.5 on 2026-05-18 19:39

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4)),
                ('product', models.UUIDField(default=uuid.uuid4)),
                ('seller', models.UUIDField(default=uuid.uuid4)),
                ('event', models.CharField(choices=[('PRODUCT_CREATED', 'Создано'), ('PRODUCT_EDITED', 'Отредактировано'), ('PRODUCT_DELETED', 'Удалено')], max_length=32)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
