# Generated by Django 5.2.14 on 2026-06-03 10:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBlockingReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Идентификатор (генерируется автоматически)', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Текст причины блокировки')),
                ('hard_block', models.BooleanField(default=False, verbose_name='Перманентная блокировка')),
            ],
            options={
                'verbose_name': 'Причина блокировки',
                'verbose_name_plural': 'Причины блокировок',
                'db_table': 'product_blocking_reasons',
            },
        ),
        migrations.CreateModel(
            name='ProductModeration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField(unique=True, verbose_name='ID товара в B2B')),
                ('seller_id', models.UUIDField(verbose_name='ID продавца')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('IN_REVIEW', 'В работе'), ('MODERATED', 'Промодерировано'), ('BLOCKED', 'Заблокировано'), ('HARD_BLOCKED', 'Жесткая блокировка')], default='PENDING', max_length=20, verbose_name='Статус модерации')),
                ('queue_priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Приоритет очереди (1-4)')),
                ('json_before', models.JSONField(blank=True, null=True, verbose_name='Состояние товара ДО изменений')),
                ('json_after', models.JSONField(verbose_name='Текущее состояние товара (JSON)')),
                ('moderator_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий модератора')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('date_moderation', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего решения модератора')),
                ('blocking_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderations', to='app.productblockingreason', verbose_name='Причина блокировки')),
                ('moderator_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Модерация товара',
                'verbose_name_plural': 'Модерация товаров',
                'db_table': 'product_moderation',
            },
        ),
        migrations.CreateModel(
            name='ProductModerationFieldReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(choices=[('title', 'Название'), ('description', 'Описание'), ('product_images', 'Изображения товара'), ('category', 'Категория'), ('sku_name', 'Название SKU'), ('sku_image', 'Изображение SKU'), ('sku_price', 'Цена SKU')], max_length=50, verbose_name='Название поля')),
                ('sku_id', models.UUIDField(blank=True, null=True, verbose_name='ID конкретного SKU (null = замечание к товару)')),
                ('comment', models.TextField(verbose_name='Комментарий модератора')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product_moderation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_reports', to='app.productmoderation', verbose_name='Запись модерации')),
            ],
            options={
                'verbose_name': 'Отчет по полю модерации',
                'verbose_name_plural': 'Отчеты по полям модерации',
                'db_table': 'product_moderation_field_report',
            },
        ),
        migrations.DeleteModel(
            name='Moderation',
        ),
        migrations.AddIndex(
            model_name='productmoderation',
            index=models.Index(fields=['status', 'queue_priority'], name='product_mod_status_9f7621_idx'),
        ),
        migrations.AddIndex(
            model_name='productmoderation',
            index=models.Index(fields=['seller_id'], name='product_mod_seller__92a840_idx'),
        ),
        migrations.AddConstraint(
            model_name='productmoderation',
            constraint=models.CheckConstraint(condition=models.Q(('queue_priority__gte', 1), ('queue_priority__lte', 4)), name='check_queue_priority_range'),
        ),
        migrations.AddIndex(
            model_name='productmoderationfieldreport',
            index=models.Index(fields=['product_moderation', 'field_name'], name='product_mod_product_10ad38_idx'),
        ),
    ]
