# Generated by Django 5.2.14 on 2026-06-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_productblockingreason_productmoderation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmoderation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает'), ('IN_REVIEW', 'В работе'), ('APPROVED', 'Промодерировано'), ('BLOCKED', 'Заблокировано'), ('HARD_BLOCKED', 'Жесткая блокировка')], default='PENDING', max_length=20, verbose_name='Статус модерации'),
        ),
    ]
