# Generated by Django 5.2.14 on 2026-06-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_productmoderation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productblockingreason',
            options={'ordering': ['title'], 'verbose_name': 'Причина блокировки', 'verbose_name_plural': 'Причины блокировок'},
        ),
        migrations.AddField(
            model_name='productblockingreason',
            name='code',
            field=models.CharField(default='a', help_text='Уникальный код причины (например, FORBIDDEN_GOODS)', max_length=64, unique=True, verbose_name='Код причины'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productblockingreason',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание причины'),
        ),
        migrations.AddField(
            model_name='productblockingreason',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
    ]
